import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


function Index({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <h1>Home Page</h1>
      <div className='grid grid-col md:grid-cols-3 gap-4'>
        {
          products.map((product) => {
            return (
              <div key={product.uuid}>

                <Link href={`/product/${product.uuid}`}>
                  <div className='bg-white p-4' >
                    <Image
                      src={`https://api.h2o.ng${product.images['500']}`}
                      alt="Picture of the author"
                      width={500}
                      height={500}
                    />
                    <div className='text-center font-semibold p-4'>
                      <h1> {product.title}</h1>
                      <h1> {product.price} </h1>
                    </div>
                  </div></Link>
              </div>
            )
          })
        }</div>
    </div>
  )
}

export default Index


export async function getServerSideProps() {
  const response = await fetch('https://api.h2o.ng/api/client/products')
  const { data } = await response.json()

  return {
    props: {
      products: data.products.data
    }
  }
}
